version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"

    groups:
      all-major-updates:
        update-types:
          - "major"

      all-minor-updates:
        update-types:
          - "minor"
          - "patch"

    open-pull-requests-limit: 10

    commit-message:
      prefix: "deps"
      include: "scope"
